# Generated by Django 5.2.4 on 2025-08-04 04:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_contactmessage_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
