# Generated by Django 5.2.4 on 2025-10-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_placementdrive_package_aptitudetest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudetest',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.staffprofile'),
        ),
    ]
