# Generated by Django 5.2.4 on 2025-10-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_aptitudetest_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
