# Generated by Django 5.2.4 on 2025-10-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_staffprofile_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='CSD', max_length=50),
            preserve_default=False,
        ),
    ]
